
#pragma once

#include "MoreOptionsDlg.h"
#include "InputConfigDlg.h"
#include "Useful.h"
#include "BitmapFile.h"

struct BBOX
{
	float x1, y1, x2, y2;
};

enum CSVFORMAT
{
	CSV_NOT_SET=0,
	CSV_MODEL_A, // csv's generated by your pre-trained models, model 'A'.
	CSV_MODEL_B,
	CSV_CLASSIFIED,
	CSV_PRELABELLED_1,
};

/* crop zones idea - special program mode.
could allow user to specify crop_zone bounding box, same process as any other class bbox.
Then when saving to CSV file, for every crop zone annotation it would export the cropped bitmap, and add to the csv file the (translated) annotations for it.
this would be a one way process once the cropped bitmaps are exported and you've started using the new csv file. (but exported bitmaps could be deleted and done again).
*/

struct SOURCELINEREPEATS
{
	// 'source line repeats' - data thats common for all csv lines relating to the same picture (filename group).
	// data here is read in from csv lines and **NEVER** modified afterwards (modified annotation data is kept in CLASSIFIEDLINE).
	// 
	// one buffer pointer for the entire filename group? I did this but it caused problems when merging, so not doing it anymore.
	int   Time_Stamp;
	char *pfile_name;
	int   Width, Height;
	int   Pic_classified;	// classified status from the csv line, not used in the UI. In the UI FILENAMEGROUP::Classified is the flag used.
	int   PictureCode;		// enum PICTURECODE
	int   ColourCode;		// enum COLOURCODE
};

struct SOURCELINE			// a single 'source csv line' (i.e. read in from the original csv file) 
{
	BYTE rsvd_best, rsvd_id;// used in FixAndCropPictures.
//	short rsvd_best;

	int   FilenameCount;
	SOURCELINEREPEATS Repeats;
	int   model_code;		// which model generated this annotation.
	int   Confidence;		// (only used for merging annotations from different models).
	int   ClassId;			// negative id signifies a 'negative' picture.
	int   DebugCode;		// used to display merging decisions in the UI.
	BBOX  Box;
};

struct SOURCELINE_CONTAINER
{
	SOURCELINE *pCsvLns;	// list - the source lines for *all* loaded csv files.
	int   Num, Max;
	int   NumFilenames;
	int   EstimateNum, LargestFnGrp;
	int   Format;
	char *pPreviousFilename;
	void Initialise()
	{	Num = Max = 0;
		EstimateNum = 0;
		pCsvLns = nullptr;	// memory is realloc'ed and kept for program lifetime.
	}
	void Reset()
	{	Num = NumFilenames = LargestFnGrp = 0;
		pPreviousFilename = nullptr;
		Format = CSVFORMAT::CSV_NOT_SET;
	}
	void FreeMem()
	{	free(pCsvLns);
	}
};

#define SELECTION_EDITING		10
#define SELECTION_HIGHLIGHT		20
#define ANY_SELECTION_TYPE		30

#define AUI_MIN_SIZE_THRESHOLD		(1<<0)
#define AUI_SPECIAL_CATEGORY		(1<<1)
#define AUI_HIDDEN_BY_OVERLAP		(1<<2) // also known as 'all probabilities'.
struct ANNOTATION_UI
{
	// info related to displaying and selecting the annotation in the UI, i.e, data that is *not* read from, or saved to, the CSV file. Its a wasteful having
	// a ANNOTATION_UI in each CLASSIFIEDLINE, because we only need this data for the CLASSIFIEDLINE's currently displayed in the UI. However, having it in every CLASSIFIEDLINE
	// makes the code very simple so its worth the wasted memory.
	// (note to me - cant use a ANNOTATION_UI pointer because the CLASSIFIEDLINE elements are copied and shuffled around during editing).
	RECT Screen;		// screen coordinates.
	int  Selected;		// selected by SELECTION_EDITING or SELECTION_HIGHLIGHT.
	int  auiFlags;
	int  AllProbsIndex;	// index to accompany AUI_HIDDEN_BY_OVERLAP flag.
};

struct CLASSIFIEDLINE
{
	ANNOTATION_UI Anno_UI;
#ifdef ALLOW_ANNOTATION_FILTER
	int  AnnotationFilter;	// only used during yolo export.
#endif
	int  ClassId;			// must be signed as we can have negative class_id to signify a 'negative' image.
	int  Model_Code;
	int  DebugCode;
	BBOX box;
};

#define NUM_SPARE_ANNOTATIONS	12
struct CLASSIFIEDLINE_CONTAINER
{
	CLASSIFIEDLINE *pLines;	// list - lines which have been 'classified', i.e. edited in the GUI.
	int Max, Num, NumSpare;

	void Initialise()
	{	Num = Max = 0;
		pLines = nullptr;	// memory is realloc'ed and kept for program lifetime.
	}
	void Reset()
	{	Num = 0;
		NumSpare = NUM_SPARE_ANNOTATIONS;
	}
	void FreeMem()
	{	free(pLines);
	}
};

struct CSVBACKUP
{
	char      Folder[MAX_PATH];
	ULONGLONG TickCount;
};

struct CANNOPATHS
{
	char PictureFolder[MAX_PATH];
	char ModelCsv[MAX_PATH];
	char ClassifiedCsv[MAX_PATH];
};

enum CLASSIFIED_STATUS
{
	//NOT_CLASSIFIED = 0, not classified is zero
	CLASSIFIED_REFUSE = 1,
	CLASSIFIED_ACCEPT,
	CLASSIFIED_SPECIAL,	// could have more classified accept codes, if for example doing a quick job or a perfect job.
	CLASSIFIED_NUM_ENTRIES,
};

struct FILENAMEGROUP
{
	SOURCELINEREPEATS *pPicInfo;

	// source lines - The original csv lines for this filename group.
	SOURCELINE *pSourceLines;
	int NumSourceLines;

	// ..and the classified lines ..ie the editted/classified annotations for this picture.
	CLASSIFIEDLINE *pClsfdLines;
	int NumClsfdLines, MaxClsfdLines;
	int Classified;	// CLASSIFIED_STATUS
	int Timestamp;
};

struct FILENAMEGROUP_ALL
{
	FILENAMEGROUP *pFNG;
	int Num, Max;

	void Initialise()
	{	Num = Max = 0;
		pFNG = nullptr;	// memory is realloc'ed and kept for program lifetime.
	}
	void Reset()
	{	Num = 0;
	}
	void FreeMem()
	{	free(pFNG);
	}
};

struct FILENAMEGROUP_FILTERED
{
	FILENAMEGROUP **ppFNG;	// list of pointers, as per the current filter criteria.
	int Num, Max;
	int CurrentIdx, SkipIncrements;

	void Initialise()
	{	Num = Max = 0;
		ppFNG = nullptr;	// memory is realloc'ed and kept for program lifetime.
	}
	void Reset()
	{	Num = CurrentIdx = 0;
	}
	void FreeMem()
	{	free(ppFNG);
	}
};

//============================================================================================
#define VERSION_STR "ClassifyProgram_v3.0"
#define MAX_COLUMNS 64
class CAnnotations
{
private:
	PICTUREFILTERS *m_pPicFilters;

	FILENAMEGROUP_ALL        m_AllGroups;
	FILENAMEGROUP_FILTERED   m_GroupsFltr;
	SOURCELINE_CONTAINER     m_SrcLines;	// source lines (csv)
	CLASSIFIEDLINE_CONTAINER m_ClsfdLines;	// classified lines

	int        m_CsvList, m_NumCsvList;		// number csv files we have loaded
	int        m_NumColumns;				// num column headers for the last csv we loaded	
	char       m_ColumnHeaders[MAX_COLUMNS][40];
	char      *m_ppFields[MAX_COLUMNS];
	CANNOPATHS m_Path;
	BOOL       m_DoingBackup;
	CSVBACKUP  m_Backup;
	CWnd      *m_pCWnd;

	static int Static_MakeDirList_CreateBlankCsv(int IsFile, int Mode, char *pDir, char *pName, void *pData);
	static int Static_MakeDirList_LoadCsvFiles(int IsFile, int Mode, char *pDir, char *pName, void *pData);
	static int Static_MakeDirList_Interrupt(HWND hDlg);
	int  LoadNegativeSourceline(char *pBitmapPath, int DoColourTest);
	int  LoadCsv_File(int FileNum, char *pPath, int ExcludeModel, int ExcludeClassified, int &Excluded, int &AvgChrsPerLine);
	int  LoadCsv_Folder(char *pFolder, INPUT_CONFIG *pInputConfig, int *pNumClassified, int *pNumModel);
	int  SourceCsvFormattingOk();
	int  GroupRepeatValuesOk(SOURCELINE *pL1, SOURCELINE *pL2);
	int  SourceLineErrorCode(SOURCELINE *pLne);
	int  LoadCsvColumnHeaders(char **ppFields, int NumFields);
	void InitJobData(int CsvList);
	int  AllocateMemCsvLine();
	int  CsvProcessLine(char **ppFields, int NumFields, int RecurseCsvOffset);
	int  StrToNumericClassId(char *pStr, int *pclass_id);
	int  LoadClassAndBbox_PreLabelled_1(char **ppFields, int Num, SOURCELINE *pDat, int *pLoaded);
	int  LoadDataStructure_PreLabelled_1(char **ppFields, int Num, SOURCELINE *pDat, int &RecurseCsvOffset);
	int  LoadDataStructure_ModelAnnotated_A(char **ppFields, int Num, SOURCELINE *pDat);
	int  LoadDataStructure_ModelAnnotated_B(char **ppFields, int Num, SOURCELINE *pDat);
	int  LoadDataStructure_Classified(char **ppFields, int Num, SOURCELINE *pDat);
	int  WriteCsvLine(int FnGIndex, FILE *pFile, SOURCELINE *pL, int Classified, int TimeStamp, int Header);
	char *GetClassifiedCsvPath(int SaveAsDlg);
	void DoBackup(int BackupIntervalMins);
	int  AllocateFilenameGroups(int Number, int WithClassifiedLine);
	int  InitClassifiedLines(FILENAMEGROUP *pFnG);
	int  KeepFilenameGroup(FILENAMEGROUP *pFNG);
	int  Keep_ClassifiedStatus(FILENAMEGROUP *pFNG, PICTUREFILTERS *pPF);
	int  Keep_PicAspectRatio(FILENAMEGROUP *pFNG, PICTUREFILTERS *pPF);
	int  Keep_ClassIDs(FILENAMEGROUP *pFNG, PICTUREFILTERS *pPF);
	int  Keep_DebugCode(FILENAMEGROUP *pFNG, PICTUREFILTERS *pPF);
	int  Keep_ColourStatus(FILENAMEGROUP *pFNG, PICTUREFILTERS *pPF);
	int  Keep_NegativePositive(FILENAMEGROUP *pFNG, PICTUREFILTERS *pPF);
	int  Keep_PartialFilename(FILENAMEGROUP *pFNG, PICTUREFILTERS *pPF);
	int  Keep_MultiProbabilities(FILENAMEGROUP *pFNG, PICTUREFILTERS *pPF);

	void RandomiseFilenameGroups();
	char *GetDefaultFilename(char *pFilename, int NumEntries);
	int  SetSourceLineFilename(SOURCELINE *pDat, char *pFilename);
//	int  SetSourceLineRepeats(SOURCELINE *pDat, SOURCELINEREPEATS *pRepeats);
	int  SourceLineFilenameMerge();
	int  AddSpaceForCroppedAnnotations();
	int  AssignFilenameCount(int SkipErrorChecking);
	int  IntegerTo_Char(int Val, char &char_val);
	int  IntegerToShort(int Val, short &short_val);
	int  PlaceholderTypeConv(int src, int &dst);
	void CsvLineToMsgBox(char *pComment, char **ppFields, int Num, SOURCELINE *pDat=nullptr);
	void SourceClassifiedDataExchange(int source_to_classified, SOURCELINE *pSrc, CLASSIFIEDLINE *pClsf);
	void DeleteOrMove(FILENAMEGROUP *pFnG, int Delete);
	FILENAMEGROUP *InitFilenameGroup_Filtered();
	FILENAMEGROUP *InitFilenameGroup_All(int WithClassifiedLine);
	FILENAMEGROUP *GetFirstFilenameGroup(int SkipErrorChecking, MOREOPTIONS *pMO, INPUT_CONFIG *pIC);

public:
	CAnnotations();
	~CAnnotations();
	CString m_MemoryReport;

	// open
	FILENAMEGROUP *LoadCsvFile(char *pCsvFile, char *pPictureFolder, MOREOPTIONS *pMO, INPUT_CONFIG *pIC);
	FILENAMEGROUP *LoadCsvFileList(char *pCsvFolder, char *pPictureFolder, MOREOPTIONS *pMO, INPUT_CONFIG *pIC);
	FILENAMEGROUP *CreateBlankCsvFile(char *pPictureBaseFolder, char *pPictureSubFolder, MOREOPTIONS *pMO, INPUT_CONFIG *pIC);

	// navigate list
	FILENAMEGROUP *GetNext(int BackupIntervalMins, int Coarse=0);
	FILENAMEGROUP *GetPrevious(int Coarse=0);
	FILENAMEGROUP *GetEnd(int Last);
	FILENAMEGROUP *GetAtFilename(char *pFilename);
	FILENAMEGROUP *GetAtIndex(int Index);
	FILENAMEGROUP *GetAtFirstOfType(int Classified, int Forward);
	FILENAMEGROUP *GetLastLatestTimestamp();

	// filter/sort list
	FILENAMEGROUP *ApplyFilters(PICTUREFILTERS *pTheFilters);
	FILENAMEGROUP *ApplySort(int PicSortCode, int AreaHeightWidth, PICTUREFILTERS *pPicFilters);

	// all the other stuff
	void ClearJob();
	void ExportForYOLO(MOREOPTIONS *pMO);
	void StatisticsPopup(MOREOPTIONS *pMO);
	int  SaveClassifiedCsvFile(int SaveAsDlg, int Exclude_NotClassified, int Exclude_Refused, int DeleteRefusedPictures);
	char *GetClassifiedCsvPath();
	void GetPicturePath(FILENAMEGROUP *pGrp, char *pPath, int PathCount);
	int  AddClassifiedLine(FILENAMEGROUP *pFnG, BBOX *pbb);
	void ResetClassifiedLines(FILENAMEGROUP *pFnG);
	int  GetFNGIndex();
	int  GetFNGCount(int *pNum);
};

extern int  BitmapCoordinatesToBbox_Inc_Exc(int L_inclusive, int R_exclusive, int T_inclusive, int B_exclusive, int Bitmap_Width, int Bitmap_Height, BBOX *pBox);
extern void BboxToBitmapCoordinates_Inc_Exc(int &L_inclusive, int &R_exclusive, int &T_inclusive, int &B_exclusive, int Bitmap_Width, int Bitmap_Height, BBOX *pBox, int Rounding=0);
extern void BboxToPixelWdHt_Inc_Exc(int &PixelWd, int &PixelHt, int Bitmap_Width, int Bitmap_Height, BBOX *pBox, int Rounding=0);
extern void rect_BboxToBitmapCoordinates_Inc_Exc(RECT &Rect, int Bitmap_Width, int Bitmap_Height, BBOX *pBox, int Rounding=0);
extern int  BboxError(BBOX *pBox);