//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Classify.rc
//
#define IDD_CLASSIFY_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_YOLO_EXPORT          130
#define IDD_DIALOG_MSG_BOX              132
#define IDD_DIALOG_MORE_OPTIONS         134
#define IDD_DIALOG_FIND_PICTURE         136
#define IDD_DIALOG_GOTO_PICTURE         136
#define IDD_DIALOG_INPUT_PATHS          138
#define IDD_DIALOG_AI_ASSIST            140
#define IDC_EDIT_PIC_FOLDER             1001
#define IDC_BTN_PIC_FOLDER              1002
#define IDC_EDIT_BLANK_PIC_FOLDER       1003
#define IDC_BTN_BLANK_PIC_FOLDER        1004
#define IDC_BTN_LOAD_CSV                1015
#define IDC_BTN_SAVE                    1016
#define IDC_BTN_SAVE_AS                 1017
#define IDC_BTN_FILTERS_REFRESH         1018
#define IDC_EDIT_SAVE_PATH              1019
#define IDC_EDIT_INFO                   1020
#define IDC_BTN_CSV_TO_YOLO             1021
#define IDC_BTN_LIST_SORTNOW            1022
#define IDC_BTN_FIND_FILENAME           1023
#define IDC_BTN_GOTO_PICTURE            1023
#define IDC_EDIT_INPUT_PATH             1024
#define IDC_EDIT_YE_INFO                1025
#define IDC_EDIT_DEBUG                  1025
#define IDC_EDIT_TEXT_DSP               1026
#define IDC_BTN_CSV_STATISTICS          1026
#define IDC_EDIT_YE_CLASS_LIST          1026
#define IDC_EDIT_CUR_PIC_PATH           1027
#define IDC_BTN_INSTRUCTIONS            1028
#define IDC_CHECK_FIXED_DIMENSIONS      1028
#define IDC_BTN_MORE_OPTIONS            1029
#define IDC_EDIT_FIXED_WIDTH            1029
#define IDC_EDIT_FIXED_HEIGHT           1030
#define IDC_EDIT_TARGET_WIDTH           1031
#define IDC_EDIT_HILIGHT_HEIGHT         1032
#define IDC_EDIT_PIC_MIN_WIDTH          1033
#define IDC_EDIT_PIC_MIN_HEIGHT         1034
#define IDC_STATIC_FILTERS              1035
#define IDC_EDIT_TARGET_HEIGHT          1035
#define IDC_CHECK_PIC_FILTERS           1036
#define IDC_EDIT_PIC_X_RATIO            1036
#define IDC_CHECK_PIC_NEGATIVES         1037
#define IDC_CHECK_INVERSE_FILTERS       1038
#define IDC_CHECK_PIC_POSITIVES         1038
#define IDC_EDIT_PIC_MIN_BBOX           1039
#define IDC_EDIT_CLASS_IDS_CSV          1040
#define IDC_EDIT_CLASS_ID_CSV           1040
#define IDC_CHECK_CLASS_IDS_CSV         1041
#define IDC_CHECK_CLASS_ID_CSV          1041
#define IDC_EDIT_PIC_DEBUGCODE          1042
#define IDC_STATIC_OUTPUT               1043
#define IDC_CHECK_PIC_CLSFD_ACCEPT      1043
#define IDC_CHECK_PIC_CLSFD_REFUSE      1044
#define IDC_CHECK_PIC_CLSFD_NOT         1045
#define IDC_EDIT_PIC_Y_RATIO            1046
#define IDC_CHECK_PIC_MIN_DIMS          1047
#define IDC_CHECK_MIN_MAX_RATIO         1048
#define IDC_BUTTON_REFRESH_LIST         1048
#define IDC_BUTTON_YOLO_STATS           1049
#define IDC_CHECK_PIC_COLOUR_UNKNOWN    1049
#define IDC_BTN_EXPORT_PATHLIST         1050
#define IDC_CHECK_PIC_COLOUR_YES        1050
#define IDC_BTN_EXPORT_ANNOTATIONS      1051
#define IDC_CHECK_PIC_COLOUR_NO         1051
#define IDC_CHECK_BBOX_MIN_HEIGHT       1052
#define IDC_CHECK_MERGE_CSV_LIST        1052
#define IDC_EDIT_PARTIAL_FILENAME       1052
#define IDC_EDIT_BBOX_MIN_HEIGHT        1053
#define IDC_CHECK_EXCLUDE_REFUSE        1053
#define IDC_CHECK_PARTIAL_FILENAME      1053
#define IDC_CHECK_BBOX_MIN_WIDTH        1054
#define IDC_RADIO_GOTO_INDEX            1054
#define IDC_CHECK_CSV_FOLDER_EXMODEL    1054
#define IDC_CHECK_MULTI_PROB            1054
#define IDC_CHECK_EXCLUDE_NOT_CLSF      1054
#define IDC_EDIT_BBOX_MIN_WIDTH         1055
#define IDC_RADIO_GOTO_FILENAME         1055
#define IDC_CHECK_CSV_FOLDER_EXCLASSIFIED 1055
#define IDC_EDIT_GOTO_INDEX             1056
#define IDC_CHECK_ONE_PIXEL_THICK       1056
#define IDC_BUTTON_YOLO_ANCHORS         1056
#define IDC_EDIT_GOTO_FILENAME          1057
#define IDC_STATIC_FILTER_NOTES         1057
#define IDC_CHECK_PIC_CLSFD_SPECIAL     1057
#define IDC_CHECK_YE_SHOW_IDX           1058
#define IDC_EDIT_PIC_MAX_BBOX           1058
#define IDC_RADIO_GOTO_NON_CLASSIFIED   1058
#define IDC_CHECK_PIC_MINMAX_BBOX       1059
#define IDC_RADIO_GOTO_LAST_CLASSIFIED  1059
#define IDC_CHECK_PIC_DEBUGCODE         1060
#define IDC_CHECK_PIC_DEBUG_NONZERO     1061
#define IDC_RADIO_PICSORT_RANDOMISE     1063
#define IDC_RADIO_PICSORT_BBOX_COUNT    1064
#define IDC_RADIO_PICSORT_BBOX_SIZE     1065
#define IDC_RADIO_CSV_FILE              1065
#define IDC_RADIO_PICSORT_BOX_PROP_SML  1065
#define IDC_RADIO_CSV_FOLDER            1066
#define IDC_RADIO_PICSORT_TIMESTAMP     1066
#define IDC_COMBO_CSV_FILE              1067
#define IDC_RADIO_PICSORT_BOX_PIXEL_SML 1067
#define IDC_BUTTON_CSV_FILE             1068
#define IDC_RADIO_PICSORT_BOX_PROP_LRG  1068
#define IDC_COMBO_CSV_FOLDER            1069
#define IDC_EDIT_QUERY                  1069
#define IDC_RADIO_PICSORT_BOXAREA_PIXEL_LRG 1069
#define IDC_RADIO_PICSORT_BOX_PIXEL_LRG 1069
#define IDC_BUTTON_CSV_FOLDER           1070
#define IDC_EDIT_RESPONSE               1070
#define IDC_RADIO_PICSORT_PIC_AREA      1070
#define IDC_BUTTON_QUERY                1071
#define IDC_BUTTON_CSV_FILE_REM         1071
#define IDC_EDIT_AI_INFO                1072
#define IDC_BUTTON_CSV_FOLDER_REM       1072
#define IDC_BUTTON_AI_INFO              1073
#define IDC_COMBO_MODELS                1074
#define IDC_CHECK_SKIP_ERROR            1075
#define IDC_CHECK_PIC_CACHE             1076
#define IDC_BTN_CACHE_FOLDER            1077
#define IDC_EDIT_CACHE_FOLDER           1078
#define IDC_RADIO_CLASS_ID_CSV_ALL      1079
#define IDC_RADIO_CLASS_ID_CSV_ANY      1080
#define IDC_CHECK_AUTO_ANNO             1080
#define IDC_RADIO_LATEST_TIME           1081
#define IDC_CHECK_REMOVE_ASBENT_IDS     1082
#define IDC_RADIO_SORT_BOX_AREA         1083
#define IDC_RADIO_SORT_BOX_HEIGHT       1084
#define IDC_RADIO_CSV_BLANK             1084
#define IDC_RADIO_SORT_BOX_WIDTH        1085
#define IDC_CHECK_DEBUG_AUTO_ANNO       1085
#define IDC_CHECK1                      1086
#define IDC_CHECK_RGB_SEPARATION_TEST   1086

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
